- name: Ansible Jobs Create
  hosts: localhost
  tasks: 
    - name: Create Jenkins Jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: test1
        password: admin1234
        url: http://172.31.44.107:8080
        user: admin

      